# Generated by Django 5.0.4 on 2024-05-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='bmi',
            field=models.FloatField(),
        ),
    ]
