# Generated by Django 5.0.4 on 2024-07-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0002_alter_answer_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='diabetic',
            field=models.CharField(max_length=40),
        ),
    ]
